src/SmartProject/ProjectBundle/Entity/Contract.php
<?php

namespace SmartProject\ProjectBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use SmartProject\TimesheetBundle\Entity\Task\ContractInterface;

/**
 * Contract
 *
 * @ORM\Entity(repositoryClass="SmartProject\ProjectBundle\Entity\ContractRepository")
 */
class Contract extends BaseProject
{
    /**
     * @return string
     */
    public function getType()
    {
        return self::TYPE_CONTRACT;
    }

    /**
     * @return Client
     */
    public function getClient()
    {
        $project = $this->getProject();

        if ($project) {
            return $project->getClient();
        }
    }

    /**
     * @return Project
     */
    public function getProject()
    {
        /** @var Project $parent */
        $parent = $this->getParent();

        return $parent;
    }

    /**
     * @param Project $project
     *
     * @return Project
     */
    public function setProject(Project $project)
    {
        return $this->setParent($project);
    }
}

src/SmartProject/ProjectBundle/Form/ContractType.php
<?php

namespace SmartProject\ProjectBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class ContractType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add(
              'name',
              'text',
              array(
                  'label'                          => 'Name',
                  'horizontal_input_wrapper_class' => 'col-lg-9',
                  'attr'                           => array(
                      'placeholder' => 'Name',
                  ),
                  'constraints'                    => new NotBlank(),
              )
          )
          ->add(
              'slug',
              'text',
              array(
                  'label'                          => 'Slug',
                  'horizontal_input_wrapper_class' => 'col-lg-9',
                  'attr'                           => array(
                      'placeholder' => 'Slug',
                  ),
                  'required'                       => false,
              )
          )
//          ->add(
//              'project',
//              'entity',
//              array(
//                  'property'                       => 'name',
//                  'label'                          => 'Project',
//                  'horizontal_input_wrapper_class' => 'col-lg-9',
//                  'class'                          => 'SmartProject\ProjectBundle\Entity\Project',
////                  'required'                       => false,
//              )
//          )
          ->add(
              'description',
              null,
              array(
                  'label'                          => 'Description',
                  'horizontal_input_wrapper_class' => 'col-lg-9',
                  'attr'                           => array(
                      'placeholder' => 'Description',
                  ),
                  'required'                       => false,
              )
          )
//          ->add('status', null, array(
//                  'label'                          => 'Status',
//                  'horizontal_input_wrapper_class' => 'col-lg-9',
//                  'required'                       => false,
//              )
//          )
//          ->add('default', null, array(
//                  'horizontal_input_wrapper_class' => 'col-lg-9',
//                  'required'                       => false,
//              )
//          )
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class'      => 'SmartProject\ProjectBundle\Entity\Contract',
                'render_fieldset' => false,
                'show_legend'     => false,
            )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'smartproject_projectbundle_contract';
    }
}

src/SmartProject/ProjectBundle/Controller/ContractController.php
<?php

namespace SmartProject\ProjectBundle\Controller;

use SmartProject\FrontBundle\SmartProjectFrontBundle;
use SmartProject\ProjectBundle\Entity\Project;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use SmartProject\ProjectBundle\Entity\Contract;
use SmartProject\ProjectBundle\Form\ContractType;

/**
 * Contract controller.
 *
 * @Route("/contract")
 */
class ContractController extends Controller
{
    /**
     * Creates a new Contract entity.
     *
     * @Route("/new/project/{slug}", name="contract_create")
     * @Method("POST")
     * @ParamConverter("project", class="SmartProjectProjectBundle:Project")
     * @Template("SmartProjectProjectBundle:Contract:new.html.twig")
     */
    public function createAction(Request $request, Project $project)
    {
        $contract = new Contract();
        $contract->setProject($project);
        $form = $this->createCreateForm($contract);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($contract);
            $em->getFilters()->disable(SmartProjectFrontBundle::FILTER_SOFTDELETE);
            $em->flush();

            return $this->redirect($this->generateUrl('contract_show', array('slug' => $contract->getSlug())));
        }

        return array(
            'contract' => $contract,
            'form'     => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Contract entity.
     *
     * @param Contract $contract The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Contract $contract)
    {
        $form = $this->createForm(
            new ContractType(),
            $contract,
            array(
                'action' => $this->generateUrl('contract_create', array('slug' => $contract->getProject()->getSlug())),
                'method' => 'POST',
            )
        );

        return $form;
    }

    /**
     * Displays a form to create a new Contract entity.
     *
     * @Route("/new/project/{slug}", name="contract_new")
     * @Method("GET")
     * @ParamConverter("project", class="SmartProjectProjectBundle:Project")
     * @Template()
     */
    public function newAction(Project $project)
    {
        $contract = new Contract();
        $contract->setProject($project);
        $form    = $this->createCreateForm($contract);

        return array(
            'contract'    => $contract,
            'project'     => $project,
            'form'        => $form->createView(),
            'form_action' => $this->generateUrl('contract_create', array('slug' => $project->getId())),
        );
    }

    /**
     * Finds and displays a Contract entity.
     *
     * @Route("/{slug}", name="contract_show")
     * @Method("GET")
     * @ParamConverter("contract", class="SmartProjectProjectBundle:Contract")
     * @Template()
     */
    public function showAction(Contract $contract)
    {
        $deleteForm = $this->createDeleteForm($contract);

        return array(
            'contract'    => $contract,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Contract entity.
     *
     * @Route("/{slug}/edit", name="contract_edit")
     * @Method("GET")
     * @Template()
     * @ParamConverter("contract", class="SmartProjectProjectBundle:Contract")
     */
    public function editAction(Contract $contract)
    {
        $editForm   = $this->createEditForm($contract);
        $deleteForm = $this->createDeleteForm($contract);

        return array(
            'contract'    => $contract,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Creates a form to edit a Contract entity.
     *
     * @param Contract $contract The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Contract $contract)
    {
        $form = $this->createForm(
            new ContractType(),
            $contract,
            array(
                'action' => $this->generateUrl('contract_update', array('slug' => $contract->getSlug())),
                'method' => 'PUT',
            )
        );

        return $form;
    }

    /**
     * Edits an existing Contract entity.
     *
     * @Route("/{slug}", name="contract_update")
     * @Method("PUT")
     * @Template("SmartProjectProjectBundle:Contract:edit.html.twig")
     * @ParamConverter("contract", class="SmartProjectProjectBundle:Contract")
     */
    public function updateAction(Request $request, Contract $contract)
    {
        $em = $this->getDoctrine()->getManager();

        $deleteForm = $this->createDeleteForm($contract);
        $editForm   = $this->createEditForm($contract);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->getFilters()->disable(SmartProjectFrontBundle::FILTER_SOFTDELETE);
            $em->flush();

            return $this->redirect($this->generateUrl('contract_show', array('slug' => $contract->getSlug())));
        }

        return array(
            'contract'    => $contract,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Contract entity.
     *
     * @Route("/{slug}", name="contract_delete")
     * @Method("DELETE")
     * @ParamConverter("contract", class="SmartProjectProjectBundle:Contract")
     */
    public function deleteAction(Request $request, Contract $contract)
    {
        $form = $this->createDeleteForm($contract);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($contract);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('contract'));
    }

    /**
     * Creates a form to delete a Contract entity by id.
     *
     * @param Contract $contract The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Contract $contract)
    {
        $options = array(
            'render_fieldset' => false,
            'show_legend'     => false,
        );

        /** @var FormBuilder $formBuilder */
        $formBuilder = $this->createFormBuilder(null, $options)
          ->setAction($this->generateUrl('contract_delete', array('slug' => $contract->getSlug())))
          ->setMethod('DELETE');

        return $formBuilder->getForm();
    }
}

src/SmartProject/ProjectBundle/Resources/views/Contract/edit.html.twig
{% extends 'SmartProjectFrontBundle::layout.html.twig' %}

{% block headline %}
    Contract edit
{% endblock %}

{% block content_content -%}
    {{ form_start(edit_form) }}

    <div class="panel panel-default">
        <div class="panel-body">
            {{ form_rest(edit_form) }}
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-block btn-primary">
            Update
        </button>
    </div>

    {{ form_end(edit_form) }}
{% endblock %}

{% block content_sidebar %}
    {% set view_mode = 'edit' %}
    {% include 'SmartProjectProjectBundle:Contract:sidebar.html.twig' %}
{% endblock %}

{% block foot_script %}
    {{ parent() }}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.btn-contract-delete').first().click(function () {
                var form = $(this).closest('form');

                bootbox.confirm(
                        'Do you confirm contract deletion?',
                        function (result) {
                            if (result) {
                                form.submit();
                            }
                        }
                );
            });
        });
    </script>
{% endblock %}

src/SmartProject/ProjectBundle/Resources/views/Contract/new.html.twig
{% extends 'SmartProjectFrontBundle::layout.html.twig' %}

{% block headline %}
    Contract creation
{% endblock %}

{% block headline_sub %}
    {% if contract.project.client %}<a href="{{ path('client_show', {slug: contract.project.client.slug}) }}">{{ contract.project.client.name }}</a> > {% endif %}
    <a href="{{ path('project_show', {slug: contract.project.slug}) }}">{{ contract.project.name }}</a>
{% endblock %}

{% block content_content %}
    {{ form_start(form) }}

    <div class="panel panel-default">
        <div class="panel-body">
            {{ form_rest(form) }}
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-block btn-primary">
            Create
        </button>
    </div>

    {{ form_end(form) }}
{% endblock %}

{% block content_sidebar %}

    {% include 'SmartProjectProjectBundle:Project:sidebar.html.twig' %}

{% endblock %}

src/SmartProject/ProjectBundle/Resources/views/Contract/show.html.twig
{% extends 'SmartProjectFrontBundle::layout.html.twig' %}

{% block headline %}
    Contract
{% endblock %}

{% block content_content %}

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ contract.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ contract.name }}</td>
        </tr>
        <tr>
            <th>Slug</th>
            <td>{{ contract.slug }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ contract.description }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ contract.status }}</td>
        </tr>
        <tr>
            <th>Created at</th>
            <td>{{ contract.createdAt|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Updated at</th>
            <td>{{ contract.updatedAt|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Deleted at</th>
            <td>{% if contract.deletedAt %}{{ contract.deletedAt|date('Y-m-d H:i:s') }}{% endif %}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

{% block content_sidebar %}
    {% set view_mode = 'show' %}
    {% include 'SmartProjectProjectBundle:Contract:sidebar.html.twig' %}
{% endblock %}

{% block foot_script %}
    {{ parent() }}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.btn-contract-delete').first().click(function () {
                var form = $(this).closest('form');

                bootbox.confirm(
                        'Do you confirm contract deletion?',
                        function (result) {
                            if (result) {
                                form.submit();
                            }
                        }
                );
            });
        });
    </script>
{% endblock %}

src/SmartProject/ProjectBundle/Resources/views/Contract/sidebar.html.twig
<div class="btn-group btn-group-justified buttons">
    <a href="{{ path('contract_edit', { 'slug': contract.slug }) }}" class="btn btn-primary btn-block"><span
                class="glyphicon glyphicon-pencil"></span> Edit contract</a>
    <a href="{{ path('contract_new', { 'slug': contract.slug }) }}" class="btn btn-success btn-block"><span
                class="glyphicon glyphicon-plus-sign"></span> Add contract</a>
</div>

<br/>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Summary</h3>
    </div>

    <table class="table table-striped table-hover">
        <tr>
            <th>Client</th>
            <td>
                {% if contract.project.client %}
                    <a href="{{ path('client_show', {slug: contract.project.client.slug}) }}">{{ contract.project.client.name }}</a>
                {% else %}
                    N/A
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Project</th>
            <td>
                {% if contract.project %}
                    <a href="{{ path('project_show', {slug: contract.project.slug}) }}">{{ contract.project.name }}</a>
                {% else %}
                    N/A
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Manager</th>
            <td>
                {% if contract.manager is defined %}
                    <a href="{{ path('user_show', {id: contract.manager.id}) }}">{{ contract.manager.name }}</a>
                {% else %}
                    N/A
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Created at</th>
            <td>{{ contract.createdAt|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Updated at</th>
            <td>{{ contract.updatedAt|date('Y-m-d H:i:s') }}</td>
        </tr>
    </table>
</div>

{% if contract.description|trim %}
    <div class="panel panel-default">
        {% if contract.description|trim %}
            <div class="panel-body">
                {{ contract.description }}
            </div>
        {% endif %}
    </div>
{% endif %}

{% if delete_form is defined %}
    {{ form_start(delete_form) }}
    <a class="btn btn-block btn-danger btn-contract-delete">Delete contract</a>
    {{ form_end(delete_form) }}
{% endif %}